"use client";


import {
  FileSpreadsheet,
  FileText,
} from "lucide-react";


import {
  toast,
} from "sonner";


import * as XLSX from "xlsx";


import jsPDF from "jspdf";

import autoTable from "jspdf-autotable";



interface WinnerItem {

  rank:number;

  candidateName:string;

  categoryName:string;

  votes:number;

}



interface Props {

  eventName:string;

  winners:WinnerItem[];

}



const COLORS = {

green:"#0F3D2E",

greenDark:"#0A2A1F",

gold:"#D4AF37",

cream:"#F8F5EF",

};





export default function WinnerExport({

eventName,

winners,

}:Props){





function groupByCategory(){


const grouped:any={};



winners.forEach(
(item)=>{


if(!grouped[item.categoryName]){

grouped[item.categoryName]=[];

}



grouped[item.categoryName].push(item);


}

);



return grouped;


}









function exportExcel(){


const rows = winners.map(
(item)=>({


Rank:item.rank,

Category:item.categoryName,

Candidate:item.candidateName,

Votes:item.votes,


})

);



const sheet =
XLSX.utils.json_to_sheet(
rows
);



sheet["!cols"]=[

{
wch:10
},

{
wch:25
},

{
wch:35
},

{
wch:15
},

];



const workbook =
XLSX.utils.book_new();



XLSX.utils.book_append_sheet(

workbook,

sheet,

"Official Winners"

);



XLSX.writeFile(

workbook,

`${eventName}-Official-Winners.xlsx`

);



toast.success(
"Excel winners report generated"
);



}










function exportPDF(){


const doc =
new jsPDF(
"portrait",
"mm",
"A4"
);



const width =
doc.internal.pageSize.width;




/*
 HEADER
*/


doc.setFillColor(
15,
61,
46
);


doc.rect(

0,

0,

width,

45,

"F"

);



doc.setTextColor(
255,
255,
255
);



doc.setFontSize(18);


doc.text(

"BASILAN STATE COLLEGE",

width/2,

15,

{
align:"center"
}

);



doc.setFontSize(13);


doc.text(

"SUPREME STUDENT COUNCIL",

width/2,

24,

{
align:"center"
}

);



doc.setFontSize(12);


doc.text(

eventName.toUpperCase(),

width/2,

34,

{
align:"center"
}

);





/*
 TITLE
*/


doc.setTextColor(

10,

42,

31

);



doc.setFontSize(16);



doc.text(

"PEOPLE'S CHOICE AWARD",

width/2,

60,

{
align:"center"
}

);



doc.setFontSize(13);



doc.text(

"OFFICIAL WINNERS REPORT",

width/2,

69,

{
align:"center"
}

);





/*
 DESCRIPTION
*/


doc.setFontSize(10);


const description =

"This official report presents the ranking of candidates based on accumulated votes during Parageyan 2026 People's Choice Award. Candidates are listed according to their respective categories and final vote standings.";



doc.text(

description,

20,

85,

{
maxWidth:170
}

);





let y = 105;




Object.entries(
groupByCategory()

)

.forEach(
([category,list]:any)=>{





/*
 CATEGORY HEADER
*/


doc.setFillColor(

212,

175,

55

);



doc.roundedRect(

20,

y-7,

170,

12,

2,

2,

"F"

);



doc.setTextColor(

10,

42,

31

);



doc.setFontSize(13);


doc.text(

category.toUpperCase(),

105,

y+1,

{
align:"center"
}

);




y += 10;





autoTable(

doc,

{


startY:y,


head:[

[
"RANK",
"CANDIDATE",
"VOTES"
]

],



body:

list.map(
(item:any)=>([


item.rank===1
?
"🏆 #1"
:
`#${item.rank}`,



item.candidateName,


`${item.votes} Votes`


])

),




theme:"grid",




headStyles:{


fillColor:[

10,

42,

31

],


textColor:[

255,

255,

255

],


fontStyle:"bold",

},




bodyStyles:{


fillColor:[

248,

245,

239

],


textColor:[

10,

42,

31

],

},




alternateRowStyles:{


fillColor:[

255,

255,

255

],

},



}


);





y =
(doc as any)
.lastAutoTable.finalY + 18;



}

);








/*
 FOOTER
*/


doc.setFontSize(10);


doc.setTextColor(

100,

100,

100

);



doc.text(

"Generated by SSC Hub Admin Console",

width/2,

285,

{
align:"center"
}

);



doc.save(

`${eventName}-Official-Winners.pdf`

);



toast.success(

"PDF winners report generated"

);


}









return (

<div className="
flex
gap-3
">


<button

onClick={exportExcel}

className="
flex
items-center
gap-2
rounded-xl
bg-[#0A2A1F]
px-4
py-2
text-white
text-sm
font-semibold
"

>


<FileSpreadsheet size={16}/>

Excel

</button>





<button

onClick={exportPDF}

className="
flex
items-center
gap-2
rounded-xl
bg-[#D4AF37]
px-4
py-2
text-[#0A2A1F]
text-sm
font-semibold
"

>


<FileText size={16}/>

PDF

</button>



</div>

);


}